/**
 * Lightning Network payment payload for the Exact scheme.
 *
 * Contains the payment preimage which serves as proof of payment
 * after a Lightning invoice has been successfully paid.
 */
export type ExactLightningPayload = {
  /**
   * Hex-encoded payment preimage (32 bytes = 64 hex characters).
   * This is the secret revealed when a Lightning payment is settled,
   * and serves as cryptographic proof that payment was made.
   */
  preimage: string;
};

/**
 * Extra fields included in Lightning payment requirements.
 *
 * The resource server generates a BOLT11 invoice and includes it here so
 * the client knows exactly which invoice to pay via NWC.
 */
export type LightningPaymentRequirementsExtra = {
  /**
   * BOLT11-encoded Lightning invoice generated by the resource server.
   * The client must pay this invoice to fulfil the payment requirement.
   */
  invoice: string;
  paymentMethod: string;
};


/**
 * Minimal interface for a Lightning wallet capable of paying BOLT11 invoices
 * (client-side)
 *
 * Any object implementing these methods is accepted (e.g. NWCClient).
 */
export interface Wallet {
  /**
   * Pay a BOLT11 invoice and return the payment preimage on success.
   * Used by the client-side scheme implementation.
   */
  payInvoice(args: { invoice: string }): Promise<{ preimage: string }>;

}
